### PR TITLE
Backpropagation with F-adjoint

### PR DESCRIPTION
**Pull request by ahmadbougham**
# Description:

- I have added a forked file named (readme_Fadjoint)
- In this file, I propose to you a simple method to implement the back-propagation algorithm

### CODE REVIEW

**Comment by gehasel** [comment]
Hey, thanks for your interest in my project.
It looks like you developed an alternative way of describing backpropagation? That's pretty neat.
I created this mostly for educational purposes and as I am also just writing my thesis, so unfortunately right now, I do not have time to look into your proposal.
If there is anything else I can help you with, feel free to reach out!

**Comment by ahmadbougham** [comment]
Thank you very much for you response. In fact, the backpropagation is exactly a kind of adjoint of the feed-forward propagation. So, it is natural that with the F-propagation and F-adjoint propagation one may recover the backpropagation. Now, I am writing some project in my github to highlight this method, so I ask you kindly to take a look on it and let me know your feedback.

**Comment by ahmadbougham** [comment]
Thank you very much for you response. In fact, the backpropagation is exactly a kind of adjoint of the feed-forward propagation. So, it is natural that with the F-propagation and F-adjoint propagation one may recover the backpropagation. Now, I am writing some project in my github to highlight this method, so I ask you kindly to take a look on it and let me know your feedback.

**Comment by ahmadbougham** [comment]
Thank you very much for you response. In fact, the backpropagation is exactly a kind of adjoint of the feed-forward propagation. So, it is natural that with the F-propagation and F-adjoint propagation one may recover the backpropagation. Now, I am writing some project in my github to highlight this method, so I ask you kindly to take a look on it and let me know your feedback.

**Pull request closed without merging**
